/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author xsyyy
 */
public class ProfessorAddJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorAddJPanel
     */
    public ProfessorAddJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCourse1 = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        lblCourseCode = new javax.swing.JLabel();
        txtCourseCode = new javax.swing.JTextField();
        lblCourseCata = new javax.swing.JLabel();
        txtCourseCata = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboxFall = new javax.swing.JCheckBox();
        cboxSpring = new javax.swing.JCheckBox();
        cbox2023 = new javax.swing.JCheckBox();
        cbox2024 = new javax.swing.JCheckBox();
        cbox2025 = new javax.swing.JCheckBox();
        cboxMonday = new javax.swing.JCheckBox();
        cboxTuesday = new javax.swing.JCheckBox();
        cboxWednesday = new javax.swing.JCheckBox();
        cboxThursday = new javax.swing.JCheckBox();
        cboxFriday = new javax.swing.JCheckBox();
        cboxSaturday = new javax.swing.JCheckBox();
        cboxSunday = new javax.swing.JCheckBox();
        cboxAm1 = new javax.swing.JCheckBox();
        cboxAm2 = new javax.swing.JCheckBox();
        cboxAm3 = new javax.swing.JCheckBox();
        cboxPm1 = new javax.swing.JCheckBox();
        cboxPm2 = new javax.swing.JCheckBox();
        cboxPm3 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescr = new javax.swing.JTextArea();
        Save = new javax.swing.JButton();

        lblCourse1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCourse1.setText("Add Course Detail");

        lblCourseName.setText("Course Name:");

        lblCourseCode.setText("Course Code:");

        lblCourseCata.setText("Course Catalog:");

        jLabel1.setText("Semester: ");

        jLabel2.setText("Year:");

        jLabel3.setText("Hour:");

        jLabel4.setText("Weekday:");

        jLabel5.setText("Course Description:");

        cboxFall.setText("Fall");

        cboxSpring.setText("Spring");

        cbox2023.setText("2023");

        cbox2024.setText("2024");

        cbox2025.setText("2025");

        cboxMonday.setText("Monday");

        cboxTuesday.setText("Tuesday");

        cboxWednesday.setText("Wednesday");

        cboxThursday.setText("Thursday");

        cboxFriday.setText("Friday");

        cboxSaturday.setText("Saturday");

        cboxSunday.setText("Sunday");

        cboxAm1.setText("0000-0300");

        cboxAm2.setText("0400-0700");

        cboxAm3.setText("0800-1100");

        cboxPm1.setText("1200-1500");

        cboxPm2.setText("1600-1900");

        cboxPm3.setText("2000-2300");

        txtDescr.setColumns(20);
        txtDescr.setRows(5);
        jScrollPane1.setViewportView(txtDescr);

        Save.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(lblCourseCata, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCourseCata, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxFall)
                                    .addComponent(cbox2023)
                                    .addComponent(cboxMonday))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxSpring)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbox2024)
                                        .addGap(36, 36, 36)
                                        .addComponent(cbox2025))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cboxTuesday)
                                        .addGap(19, 19, 19)
                                        .addComponent(cboxWednesday)
                                        .addGap(27, 27, 27)
                                        .addComponent(cboxThursday)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboxFriday)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboxSaturday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboxSunday))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboxAm1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxAm2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxAm3)
                                .addGap(18, 18, 18)
                                .addComponent(cboxPm1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxPm2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxPm3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCourseCata, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCourseCata, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboxFall)
                    .addComponent(cboxSpring))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbox2023)
                    .addComponent(cbox2024)
                    .addComponent(cbox2025))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboxMonday)
                    .addComponent(cboxTuesday)
                    .addComponent(cboxWednesday)
                    .addComponent(cboxThursday)
                    .addComponent(cboxFriday)
                    .addComponent(cboxSaturday)
                    .addComponent(cboxSunday))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboxAm1)
                        .addComponent(cboxAm2)
                        .addComponent(cboxAm3)
                        .addComponent(cboxPm1)
                        .addComponent(cboxPm2)
                        .addComponent(cboxPm3)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JCheckBox cbox2023;
    private javax.swing.JCheckBox cbox2024;
    private javax.swing.JCheckBox cbox2025;
    private javax.swing.JCheckBox cboxAm1;
    private javax.swing.JCheckBox cboxAm2;
    private javax.swing.JCheckBox cboxAm3;
    private javax.swing.JCheckBox cboxFall;
    private javax.swing.JCheckBox cboxFriday;
    private javax.swing.JCheckBox cboxMonday;
    private javax.swing.JCheckBox cboxPm1;
    private javax.swing.JCheckBox cboxPm2;
    private javax.swing.JCheckBox cboxPm3;
    private javax.swing.JCheckBox cboxSaturday;
    private javax.swing.JCheckBox cboxSpring;
    private javax.swing.JCheckBox cboxSunday;
    private javax.swing.JCheckBox cboxThursday;
    private javax.swing.JCheckBox cboxTuesday;
    private javax.swing.JCheckBox cboxWednesday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourse1;
    private javax.swing.JLabel lblCourseCata;
    private javax.swing.JLabel lblCourseCode;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JTextField txtCourseCata;
    private javax.swing.JTextField txtCourseCode;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextArea txtDescr;
    // End of variables declaration//GEN-END:variables
}
