/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Person;
import model.Student;
/**
 *
 * @author xupeihan
 */
public class StudentProfileJPanel extends javax.swing.JPanel {
    ImageIcon image;
    Student student;
            
    /**
     * Creates new form TestJPanel
     */
    public StudentProfileJPanel(Student student) {
        initComponents();
        this.student=student;
        txtsname.setText(student.getName());
        txtgender.setText(student.getGender());
        txtage.setText(String.valueOf(student.getAge()));
        txtEmail.setText(student.getEmail());
        txtregion.setText(student.getRegion());
        txtlanguage.setText(student.getLanguage());
        txtbirthday.setText(student.getBirthday().toString());
        txtstudentID.setText(String.valueOf(student.getStudentID()));
        txtusername.setText(student.getsUsername());
        txtGPA.setText(String.valueOf(student.getGPA()));
        txtGraduate.setText(String.valueOf(student.isIsGraduate()));
        lblImage.setIcon(student.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentProfileJPanel = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        btnAddPhoto = new javax.swing.JButton();
        txtsname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtGraduate = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtage = new javax.swing.JTextField();
        lblAge1 = new javax.swing.JLabel();
        txtregion = new javax.swing.JTextField();
        lblAge2 = new javax.swing.JLabel();
        txtlanguage = new javax.swing.JTextField();
        lblbirthday = new javax.swing.JLabel();
        txtbirthday = new javax.swing.JTextField();
        lblStuProfile = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblstudentID = new javax.swing.JLabel();
        txtstudentID = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        lblGPA = new javax.swing.JLabel();
        txtGPA = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        btnGraduate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtGradStatus = new javax.swing.JTextField();
        btnsUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(251, 238, 172));

        StudentProfileJPanel.setBackground(new java.awt.Color(251, 238, 172));
        StudentProfileJPanel.setEnabled(false);

        lblImage.setBackground(new java.awt.Color(204, 204, 0));
        lblImage.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblImage.setBorder(new javax.swing.border.MatteBorder(null));

        btnAddPhoto.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAddPhoto.setText("Please touch the button");
        btnAddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPhotoActionPerformed(evt);
            }
        });

        txtsname.setEnabled(false);

        txtEmail.setEnabled(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtGraduate.setEnabled(false);
        txtGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGraduateActionPerformed(evt);
            }
        });

        txtgender.setEnabled(false);

        btnSave.setBackground(new java.awt.Color(117, 194, 246));
        btnSave.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtage.setEnabled(false);

        lblAge1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblAge1.setText("Region:");

        txtregion.setEnabled(false);

        lblAge2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblAge2.setText("Language:");

        txtlanguage.setEnabled(false);

        lblbirthday.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblbirthday.setText("Birthday:");

        txtbirthday.setEnabled(false);

        lblStuProfile.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblStuProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStuProfile.setText("STUDENT PROFILE");

        lblName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblName.setText("Name:");

        lblEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblEmail.setText("Email:");

        lblstudentID.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblstudentID.setText("Student ID:");

        txtstudentID.setEnabled(false);

        lblUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblUsername.setText("Username:");

        txtusername.setEnabled(false);

        lblGPA.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblGPA.setText("GPA:");

        txtGPA.setEnabled(false);

        lblAge.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblAge.setText("Age:");

        lblStatus.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblStatus.setText("Status:");

        lblGender.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblGender.setText("Gender:");

        lblPicture.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblPicture.setText("Picture:");

        btnGraduate.setBackground(new java.awt.Color(117, 194, 246));
        btnGraduate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnGraduate.setText("Apply for graduate");
        btnGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Status:");

        txtGradStatus.setEnabled(false);

        btnsUpdate.setBackground(new java.awt.Color(117, 194, 246));
        btnsUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnsUpdate.setText("Update");
        btnsUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentProfileJPanelLayout = new javax.swing.GroupLayout(StudentProfileJPanel);
        StudentProfileJPanel.setLayout(StudentProfileJPanelLayout);
        StudentProfileJPanelLayout.setHorizontalGroup(
            StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStuProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName)
                            .addComponent(lblEmail)
                            .addComponent(lblStatus)
                            .addComponent(lblGender)
                            .addComponent(lblAge)
                            .addComponent(lblAge1)))
                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAge2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtlanguage, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(txtGradStatus)
                    .addComponent(txtEmail)
                    .addComponent(txtGraduate)
                    .addComponent(txtgender)
                    .addComponent(txtage)
                    .addComponent(txtregion)
                    .addComponent(txtsname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                        .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsername)
                            .addComponent(lblstudentID)
                            .addComponent(lblGPA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGPA, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(txtusername, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(txtstudentID)))
                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblbirthday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                .addComponent(lblPicture)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                .addComponent(btnsUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40))
            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(btnGraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StudentProfileJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtGPA, txtlanguage, txtusername});

        StudentProfileJPanelLayout.setVerticalGroup(
            StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentProfileJPanelLayout.createSequentialGroup()
                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentProfileJPanelLayout.createSequentialGroup()
                        .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblStuProfile)
                                .addGap(24, 24, 24)
                                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtstudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtGraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(lblstudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPicture)))
                        .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAge1)
                                    .addComponent(txtregion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAge2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtGradStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblName))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lblEmail))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(lblStatus))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(lblGender))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(lblAge)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnGraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsUpdate)
                    .addComponent(btnSave))
                .addGap(40, 40, 40))
        );

        StudentProfileJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEmail, txtGPA, txtGradStatus, txtGraduate, txtage, txtbirthday, txtgender, txtlanguage, txtregion, txtsname, txtstudentID, txtusername});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentProfileJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentProfileJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.Image","jpg","png");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);
        if (result==JFileChooser.APPROVE_OPTION){
            File selectedFile=file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            ImageIcon MyImage  =new ImageIcon(path);
            Image img = MyImage.getImage();
            Image newImg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
            image = new ImageIcon(newImg);
            lblImage.setIcon(image);
        }
        else if (result==JFileChooser.CANCEL_OPTION){
            System.out.println("No picture");
        }
    }//GEN-LAST:event_btnAddPhotoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGraduateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGraduateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name=txtsname.getText();
        String Gender=txtgender.getText();
        int age =Integer.parseInt(txtage.getText());
        String Email=txtEmail.getText();
        String region=txtregion.getText();
        String Language=txtlanguage.getText();
        LocalDate birthday= LocalDate.parse(txtbirthday.getText());
        int studentID=Integer.parseInt(txtstudentID.getText());
        String sUsername=txtusername.getText();
        double GPA=Double.parseDouble(txtGPA.getText());
        boolean isGraduate=Boolean.valueOf(txtGraduate.getText());

        student.setName(txtsname.getText());
        student.setGender(txtgender.getText());
        student.setAge(Integer.parseInt(txtage.getText()));
        student.setEmail(txtEmail.getText());
        student.setRegion(txtregion.getText());
        student.setLanguage(txtlanguage.getText());
        student.setBirthday(LocalDate.parse(txtbirthday.getText()));
        student.setStudentID(Integer.parseInt(txtstudentID.getText()));
        student.setsUsername(txtusername.getText());
        student.setGPA(Double.parseDouble(txtGPA.getText()));
        student.setIsGraduate(true);
        student.setImage((ImageIcon) lblImage.getIcon());

        JOptionPane.showMessageDialog(this, "Your personal information has been updated.");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduateActionPerformed
        // TODO add your handling code here:
        if(student.CheckGraduateStatus()){
            student.setAlreadyGraduated(true);
            JOptionPane.showMessageDialog(this, "Congraduation! You get your MS degree!");
        }
        else{
            JOptionPane.showMessageDialog(this, "You haven't finish your degree requrement.");
        }
    }//GEN-LAST:event_btnGraduateActionPerformed

    private void btnsUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsUpdateActionPerformed
        // TODO add your handling code here:
       txtstudentID.setEnabled(true);
        txtsname.setEnabled(true);
        txtgender.setEnabled(true);
        txtage.setEnabled(true);
        txtEmail.setEnabled(true);     
        txtregion.setEnabled(true);
        txtlanguage.setEnabled(true);
        txtbirthday.setEnabled(true);
        txtusername.setEnabled(true);
        txtGPA.setEnabled(true);
        txtGraduate.setEnabled(true);
        txtGradStatus.setEnabled(true);
    }//GEN-LAST:event_btnsUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StudentProfileJPanel;
    private javax.swing.JButton btnAddPhoto;
    private javax.swing.JButton btnGraduate;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnsUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAge1;
    private javax.swing.JLabel lblAge2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStuProfile;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblbirthday;
    private javax.swing.JLabel lblstudentID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGPA;
    private javax.swing.JTextField txtGradStatus;
    private javax.swing.JTextField txtGraduate;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtbirthday;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtlanguage;
    private javax.swing.JTextField txtregion;
    private javax.swing.JTextField txtsname;
    private javax.swing.JTextField txtstudentID;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
