/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import model.Admin;
import model.Course;
import model.Student;

/**
 *
 * @author xupeihan
 */
public class StudentViewClassJPanel extends javax.swing.JPanel {
    /**
     * Creates new form StudentViewClassJPanel
     */
    Admin admin;
    Course course;
    Student student;
    JSplitPane SplitPane;
    public StudentViewClassJPanel(Course course, Admin admin, Student student,JSplitPane SplitPane) {
        initComponents();
        this.course=course;
        this.admin=admin;
        this.student=student;
        this.SplitPane=SplitPane;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentViewClassJPanel = new javax.swing.JPanel();
        lblCourseName = new javax.swing.JLabel();
        txtcWeekDay = new javax.swing.JTextField();
        lblSemester = new javax.swing.JLabel();
        lblCourseDesc = new javax.swing.JLabel();
        txtcHour = new javax.swing.JTextField();
        lblCourseCode = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWaitlist = new javax.swing.JTable();
        lblWeekDay = new javax.swing.JLabel();
        lblCourseCatalog = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCStu = new javax.swing.JTable();
        lblHour = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblWatilist = new javax.swing.JLabel();
        txtcName = new javax.swing.JTextField();
        txtcYear = new javax.swing.JTextField();
        txtSemester = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        lblCourseDetail = new javax.swing.JLabel();
        txtcCode = new javax.swing.JTextField();
        txtcDescription = new javax.swing.JTextField();
        lblSemester1 = new javax.swing.JLabel();
        txtCourseTopic = new javax.swing.JTextField();
        txtcCatalog = new javax.swing.JTextField();

        StudentViewClassJPanel.setBackground(new java.awt.Color(251, 238, 172));

        lblCourseName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseName.setText("Course Name:");

        txtcWeekDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcWeekDayActionPerformed(evt);
            }
        });

        lblSemester.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblSemester.setText("Semester:");

        lblCourseDesc.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseDesc.setText("Course Description:");

        txtcHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcHourActionPerformed(evt);
            }
        });

        lblCourseCode.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseCode.setText("Course Code:");

        tblWaitlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student Name", "Student ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWaitlist);

        lblWeekDay.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblWeekDay.setText("WeekDay:");

        lblCourseCatalog.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseCatalog.setText("Course Catalog:");

        tblCStu.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 14)); // NOI18N
        tblCStu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student Name", "Student ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCStu);

        lblHour.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblHour.setText("Hour:");

        btnBack.setBackground(new java.awt.Color(117, 194, 246));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblWatilist.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblWatilist.setText("Waitlist:");

        txtcName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcNameActionPerformed(evt);
            }
        });

        txtcYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcYearActionPerformed(evt);
            }
        });

        txtSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSemesterActionPerformed(evt);
            }
        });

        lblYear.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblYear.setText("Year:");

        lblCourseDetail.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblCourseDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCourseDetail.setText("COURSE DETAIL");

        txtcCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcCodeActionPerformed(evt);
            }
        });

        txtcDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcDescriptionActionPerformed(evt);
            }
        });

        lblSemester1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblSemester1.setText("Topic:");

        javax.swing.GroupLayout StudentViewClassJPanelLayout = new javax.swing.GroupLayout(StudentViewClassJPanel);
        StudentViewClassJPanel.setLayout(StudentViewClassJPanelLayout);
        StudentViewClassJPanelLayout.setHorizontalGroup(
            StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentViewClassJPanelLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(lblCourseDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentViewClassJPanelLayout.createSequentialGroup()
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                        .addComponent(lblCourseName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                        .addComponent(lblCourseCode)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcCode, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentViewClassJPanelLayout.createSequentialGroup()
                                .addComponent(lblCourseDesc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                    .addComponent(lblCourseCatalog)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                    .addComponent(lblSemester1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCourseTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lblSemester)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWeekDay, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHour, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblYear, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcWeekDay, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcYear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentViewClassJPanelLayout.createSequentialGroup()
                                .addComponent(lblWatilist)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addContainerGap())))
        );

        StudentViewClassJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCourseTopic, txtSemester, txtcCatalog, txtcCode, txtcHour, txtcName, txtcWeekDay, txtcYear});

        StudentViewClassJPanelLayout.setVerticalGroup(
            StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentViewClassJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblCourseDetail)
                .addGap(28, 28, 28)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(lblCourseCatalog)
                    .addComponent(txtcName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWeekDay)
                    .addComponent(txtcWeekDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseCode)
                    .addComponent(txtcCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSemester1)
                    .addComponent(lblHour)
                    .addComponent(txtcHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSemester)
                        .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblYear)
                        .addComponent(txtcYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCourseDesc)
                    .addComponent(txtcDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWatilist))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentViewClassJPanelLayout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addContainerGap())))
        );

        StudentViewClassJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCourseTopic, txtSemester, txtcCatalog, txtcCode, txtcHour, txtcName, txtcWeekDay, txtcYear});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentViewClassJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(StudentViewClassJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcWeekDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcWeekDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcWeekDayActionPerformed

    private void txtcHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcHourActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        StudentCourseJPanel panel=new StudentCourseJPanel(SplitPane,admin,student);
        SplitPane.setRightComponent(panel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtcNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcNameActionPerformed

    private void txtcYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcYearActionPerformed

    private void txtSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemesterActionPerformed

    private void txtcCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcCodeActionPerformed

    private void txtcDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcDescriptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StudentViewClassJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseCatalog;
    private javax.swing.JLabel lblCourseCode;
    private javax.swing.JLabel lblCourseDesc;
    private javax.swing.JLabel lblCourseDetail;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblSemester1;
    private javax.swing.JLabel lblWatilist;
    private javax.swing.JLabel lblWeekDay;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTable tblCStu;
    private javax.swing.JTable tblWaitlist;
    private javax.swing.JTextField txtCourseTopic;
    private javax.swing.JTextField txtSemester;
    private javax.swing.JTextField txtcCatalog;
    private javax.swing.JTextField txtcCode;
    private javax.swing.JTextField txtcDescription;
    private javax.swing.JTextField txtcHour;
    private javax.swing.JTextField txtcName;
    private javax.swing.JTextField txtcWeekDay;
    private javax.swing.JTextField txtcYear;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
        txtcName.setText(course.getcName());
        txtcCode.setText(course.getcCode());
        txtcCatalog.setText(course.getcTopic());
        txtCourseTopic.setText(course.getcTopic());
        txtcDescription.setText(course.getcDescription());
        txtSemester.setText(course.getSemesters());
        txtcWeekDay.setText(course.getWeekdays());
        txtcHour.setText(course.getHours());
        txtcYear.setText(course.getYears());
       
    }
    private void populateTable() {
        
         txtcName.setText(course.getcName());
        txtcCode.setText(course.getcCode());
        txtcCatalog.setText(course.getcCatalog());
        txtCourseTopic.setText(course.getcTopic());
        txtcDescription.setText(course.getcDescription());
        txtSemester.setText(course.getSemesters());
        txtcWeekDay.setText(course.getWeekdays());
        txtcHour.setText(course.getHours());
        txtcYear.setText(course.getYears());
             DefaultTableModel model1 = (DefaultTableModel) tblCStu.getModel();
             model1.setRowCount(0);
             for(Student student: course.getStudentList()){
               Object [] row = new Object[2];
               row[0] = student;
      
               row[1] = student.getStudentID();
               model1.addRow(row);
             }    
               
               
             DefaultTableModel model2 = (DefaultTableModel) tblWaitlist.getModel();
             model2.setRowCount(0);
             for(Student student: course.getWaitList()){
               Object [] row = new Object[2];
               row[0] = student;
             
               row[1] = student.getStudentID();
               model2.addRow(row);
               }
    }
}
