/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.Course;

/**
 *
 * @author xupeihan
 */
public class StudentViewClassJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentViewClassJPanel
     */
    Course course;
    public StudentViewClassJPanel(Course course) {
        initComponents();
         displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentViewClassJPanel = new javax.swing.JPanel();
        lblCourseDetail = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        lblCourseDesc = new javax.swing.JLabel();
        lblCourseCode = new javax.swing.JLabel();
        lblWeekDay = new javax.swing.JLabel();
        lblCourseCatalog = new javax.swing.JLabel();
        lblHour = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtcName = new javax.swing.JTextField();
        txtSemester = new javax.swing.JTextField();
        txtcCode = new javax.swing.JTextField();
        txtcWeekDay = new javax.swing.JTextField();
        txtcTopic = new javax.swing.JTextField();
        txtcHour = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWaitlist = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourseDesc = new javax.swing.JTable();
        lblWatilist = new javax.swing.JLabel();
        txtcYear = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        txtcDescription = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        lblCourseDetail.setText("Course Detail");

        lblCourseName.setText("Course Name:");

        lblSemester.setText("Semester:");

        lblCourseDesc.setText("Course Description:");

        lblCourseCode.setText("Course Code:");

        lblWeekDay.setText("WeekDay:");

        lblCourseCatalog.setText("Course Catalog:");

        lblHour.setText("Hour:");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtcName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcNameActionPerformed(evt);
            }
        });

        txtSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSemesterActionPerformed(evt);
            }
        });

        txtcCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcCodeActionPerformed(evt);
            }
        });

        txtcWeekDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcWeekDayActionPerformed(evt);
            }
        });

        txtcTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcTopicActionPerformed(evt);
            }
        });

        txtcHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcHourActionPerformed(evt);
            }
        });

        tblWaitlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student Name", "Student ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWaitlist);

        tblCourseDesc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student Name", "Student ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCourseDesc);

        lblWatilist.setText("Waitlist:");

        txtcYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcYearActionPerformed(evt);
            }
        });

        lblYear.setText("Year:");

        txtcDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcDescriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentViewClassJPanelLayout = new javax.swing.GroupLayout(StudentViewClassJPanel);
        StudentViewClassJPanel.setLayout(StudentViewClassJPanelLayout);
        StudentViewClassJPanelLayout.setHorizontalGroup(
            StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblCourseDetail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSemester)
                    .addComponent(lblCourseName)
                    .addComponent(lblCourseDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                .addComponent(txtcName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCourseCode))
                            .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblYear)))
                        .addGap(18, 18, 18)
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcYear, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcCode, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCourseCatalog)
                            .addComponent(lblWeekDay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                .addComponent(txtcWeekDay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblHour)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcHour, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64))
                    .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                        .addComponent(txtcDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentViewClassJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWatilist)
                .addGap(80, 80, 80)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnBack)))
                .addGap(34, 34, 34))
        );
        StudentViewClassJPanelLayout.setVerticalGroup(
            StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblCourseDetail)
                .addGap(60, 60, 60)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(lblCourseCode)
                    .addComponent(lblCourseCatalog)
                    .addComponent(txtcName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemester)
                    .addComponent(lblWeekDay)
                    .addComponent(lblHour)
                    .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcWeekDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYear)
                    .addComponent(txtcYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseDesc)
                    .addComponent(txtcDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblWatilist))
                .addGap(24, 24, 24))
        );

        add(StudentViewClassJPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txtcNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcNameActionPerformed

    private void txtSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemesterActionPerformed

    private void txtcCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcCodeActionPerformed

    private void txtcWeekDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcWeekDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcWeekDayActionPerformed

    private void txtcTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcTopicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcTopicActionPerformed

    private void txtcHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcHourActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        StudentAddcourseJPanel studentAddcourseJPanel =new StudentAddcourseJPanel(admin);
        this.getParent().add(studentAddcourseJPanel ,"AdminLoading");
        CardLayout cardlayout=(CardLayout)this.getParent().getLayout();
        cardlayout.show(this.getParent(), "StudentAddcourseJPanel");
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtcYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcYearActionPerformed

    private void txtcDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcDescriptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StudentViewClassJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseCatalog;
    private javax.swing.JLabel lblCourseCode;
    private javax.swing.JLabel lblCourseDesc;
    private javax.swing.JLabel lblCourseDetail;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblWatilist;
    private javax.swing.JLabel lblWeekDay;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTable tblCourseDesc;
    private javax.swing.JTable tblWaitlist;
    private javax.swing.JTextField txtSemester;
    private javax.swing.JTextField txtcCode;
    private javax.swing.JTextField txtcDescription;
    private javax.swing.JTextField txtcHour;
    private javax.swing.JTextField txtcName;
    private javax.swing.JTextField txtcTopic;
    private javax.swing.JTextField txtcWeekDay;
    private javax.swing.JTextField txtcYear;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
       txtcName.setText(course.getcName());
       txtcCode.setText(course.getcCode());
       txtcDescription.setText(course.getcDescription());
       txtcTopic.setText(course.getcTopic());  
       txtcHour.setText(course.getHours());    
       txtcYear.setText(course.getYears());
    }
}
