/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Person;
import model.Student;
/**
 *
 * @author xupeihan
 */
public class StudentProfileJPanel extends javax.swing.JPanel {
    ImageIcon image;
    Person person;
    Student student;
            
    /**
     * Creates new form TestJPanel
     */
    public StudentProfileJPanel() {
        initComponents();
        this.person=person;
        this.student=student;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentProfileJPanel = new javax.swing.JPanel();
        lblStuProfile = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        btnAddPhoto = new javax.swing.JButton();
        txtsUsername = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtGraduate = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        lblStuProfile.setText("Student Profile");

        lblName.setText("Name:");

        lblEmail.setText("Email:");

        lblStatus.setText("Status:");

        lblGender.setText("Gender:");

        lblImage.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        lblPicture.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblPicture.setText("Picture:");

        btnAddPhoto.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnAddPhoto.setText("Please touch the button");
        btnAddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPhotoActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGraduateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentProfileJPanelLayout = new javax.swing.GroupLayout(StudentProfileJPanel);
        StudentProfileJPanel.setLayout(StudentProfileJPanelLayout);
        StudentProfileJPanelLayout.setHorizontalGroup(
            StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblStuProfile))
                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(18, 18, 18)
                                .addComponent(txtsUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStatus)
                                    .addComponent(lblGender))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtGraduate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblPicture)
                        .addGap(31, 31, 31)
                        .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave))
                            .addComponent(btnAddPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(52, 52, 52))
        );
        StudentProfileJPanelLayout.setVerticalGroup(
            StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblStuProfile)
                .addGap(35, 35, 35)
                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtsUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblStatus)
                        .addGap(18, 18, 18)
                        .addComponent(lblGender))
                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtGraduate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPicture)
                    .addComponent(btnAddPhoto))
                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(StudentProfileJPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.Image","jpg","png");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);
        if (result==JFileChooser.APPROVE_OPTION){
            File selectedFile=file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            ImageIcon MyImage  =new ImageIcon(path);
            Image img = MyImage.getImage();
            Image newImg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
            image = new ImageIcon(newImg);
            lblImage.setIcon(image);
        }
        else if (result==JFileChooser.CANCEL_OPTION){
            System.out.println("No picture");
        }

    }//GEN-LAST:event_btnAddPhotoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
          String Name=txtsUsername.getText();
          String Email=txtEmail.getText();
          String Gender=txtgender.getText();
          String isGraduate=txtGraduate.getText();
        
          person.setName(txtsUsername.getText());
          person.setEmail(txtEmail.getText());
          person.setGender(txtgender.getText());
          person.setImage((ImageIcon) lblImage.getIcon());
          student.setIsGraduate(true);
         
         
          JOptionPane.showMessageDialog(this, "Your personal information has been updated.");
          txtsUsername.setText("");
          txtEmail.setText("");
          txtgender.setText("");
          txtGraduate.setText("");


   
          System.out.println(txtsUsername.getText());

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGraduateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGraduateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StudentProfileJPanel;
    private javax.swing.JButton btnAddPhoto;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStuProfile;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGraduate;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtsUsername;
    // End of variables declaration//GEN-END:variables
}
