/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.awt.CardLayout;
import model.Admin;
import model.Student;
/**
 *
 * @author JANFAN
 */
public class StudentDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentDashboardJPanel
     */
    Student student;
    Admin admin;
    public StudentDashboardJPanel(Admin admin, Student student) {
        initComponents();
        this.admin=admin;
        this.student=student;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        workAreaPanel = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        btnShowCourse = new javax.swing.JButton();
        btnShowProfile = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();

        SplitPane.setBackground(new java.awt.Color(251, 238, 172));

        workAreaPanel.setBackground(new java.awt.Color(251, 238, 172));

        javax.swing.GroupLayout workAreaPanelLayout = new javax.swing.GroupLayout(workAreaPanel);
        workAreaPanel.setLayout(workAreaPanelLayout);
        workAreaPanelLayout.setHorizontalGroup(
            workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        workAreaPanelLayout.setVerticalGroup(
            workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(workAreaPanel);

        controlPanel.setBackground(new java.awt.Color(251, 238, 172));

        btnShowCourse.setText("Course");
        btnShowCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCourseActionPerformed(evt);
            }
        });

        btnShowProfile.setText("Profile");
        btnShowProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowProfileActionPerformed(evt);
            }
        });

        btnSignOut.setText("Sign out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignOut)
                    .addComponent(btnShowCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnShowCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnShowProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(btnSignOut)
                .addGap(24, 24, 24))
        );

        SplitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCourseActionPerformed
        // TODO add your handling code here:
        //CardLayout cardlayout=(CardLayout)this.getParent().getLayout();
        //cardlayout.show(this.getParent(),"studentDashboard");
        StudentCourseJPanel studentCourseJPanel=new StudentCourseJPanel(SplitPane,admin,student);
        SplitPane.setRightComponent(studentCourseJPanel);
    }//GEN-LAST:event_btnShowCourseActionPerformed

    private void btnShowProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowProfileActionPerformed
        // TODO add your handling code here:
        StudentProfileJPanel studentProfileJPanel=new StudentProfileJPanel(student);
        SplitPane.setRightComponent(studentProfileJPanel);
    }//GEN-LAST:event_btnShowProfileActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
        CardLayout cardlayout=(CardLayout)this.getParent().getLayout();
        cardlayout.show(this.getParent(),"studentSignIn");
    }//GEN-LAST:event_btnSignOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnShowCourse;
    private javax.swing.JButton btnShowProfile;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel workAreaPanel;
    // End of variables declaration//GEN-END:variables
}
