/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Person;
import model.Student;
/**
 *
 * @author xupeihan
 */
public class StudentProfileJPanel extends javax.swing.JPanel {
    ImageIcon image;
    Student student;
            
    /**
     * Creates new form TestJPanel
     */
    public StudentProfileJPanel(Student student) {
        initComponents();
        this.student=student;
        txtsname.setText(student.getName());
        txtgender.setText(student.getGender());
        txtage.setText(String.valueOf(student.getAge()));
        txtEmail.setText(student.getEmail());
        txtregion.setText(student.getRegion());
        txtlanguage.setText(student.getLanguage());
        txtbirthday.setText(student.getBirthday().toString());
        txtstudentID.setText(String.valueOf(student.getStudentID()));
        txtusername.setText(student.getsUsername());
        txtGPA.setText(String.valueOf(student.getGPA()));
        txtGraduate.setText(String.valueOf(student.isIsGraduate()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentProfileJPanel = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        btnAddPhoto = new javax.swing.JButton();
        txtsname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtGraduate = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtage = new javax.swing.JTextField();
        lblAge1 = new javax.swing.JLabel();
        txtregion = new javax.swing.JTextField();
        lblAge2 = new javax.swing.JLabel();
        txtlanguage = new javax.swing.JTextField();
        lblbirthday = new javax.swing.JLabel();
        txtbirthday = new javax.swing.JTextField();
        lblStuProfile = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblstudentID = new javax.swing.JLabel();
        txtstudentID = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        lblGPA = new javax.swing.JLabel();
        txtGPA = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblImage1 = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();

        lblImage.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        btnAddPhoto.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnAddPhoto.setText("Please touch the button");
        btnAddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPhotoActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGraduateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblAge1.setText("Region:");

        lblAge2.setText("Language:");

        lblbirthday.setText("Birthday:");

        lblStuProfile.setText("Student Profile");

        lblName.setText("Name:");

        lblEmail.setText("Email:");

        lblstudentID.setText("Student ID:");

        lblUsername.setText("Username:");

        lblGPA.setText("GPA:");

        lblAge.setText("Age:");

        lblStatus.setText("Status:");

        lblGender.setText("Gender:");

        lblImage1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        lblPicture.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblPicture.setText("Picture:");

        javax.swing.GroupLayout StudentProfileJPanelLayout = new javax.swing.GroupLayout(StudentProfileJPanel);
        StudentProfileJPanel.setLayout(StudentProfileJPanelLayout);
        StudentProfileJPanelLayout.setHorizontalGroup(
            StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentProfileJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblbirthday)
                .addGap(261, 261, 261))
            .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                            .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmail)
                                        .addComponent(lblName)))
                                .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                    .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblStatus)
                                        .addComponent(lblGender)
                                        .addComponent(lblAge))
                                    .addGap(18, 18, 18)
                                    .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtsname, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                        .addComponent(txtEmail)
                                        .addComponent(txtGraduate)
                                        .addComponent(txtgender)
                                        .addComponent(txtage)
                                        .addComponent(txtregion))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                        .addComponent(lblstudentID)
                                        .addGap(18, 18, 18)
                                        .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtstudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                        .addComponent(lblGPA)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                    .addComponent(lblAge2)
                                    .addGap(23, 23, 23)
                                    .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtlanguage, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                        .addComponent(txtbirthday)))))
                        .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                            .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSave)
                                .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(lblStuProfile))
                                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(lblAge1))
                                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                        .addComponent(lblPicture)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(64, 64, 64)))
        );

        StudentProfileJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtGPA, txtlanguage, txtstudentID, txtusername});

        StudentProfileJPanelLayout.setVerticalGroup(
            StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(lblbirthday)
                .addGap(18, 18, 18)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(lblStuProfile)
                    .addGap(35, 35, 35)
                    .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName)
                        .addComponent(txtsname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblstudentID)
                        .addComponent(txtstudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUsername)
                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(lblStatus))
                        .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtGraduate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblGPA)
                                .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblGender)
                                .addComponent(lblAge2)
                                .addComponent(txtlanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAge)
                                .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtregion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAge1)))
                        .addGroup(StudentProfileJPanelLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(txtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(StudentProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPicture)
                        .addComponent(btnAddPhoto))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(btnSave)
                    .addGap(36, 36, 36)))
        );

        StudentProfileJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtGPA, txtlanguage, txtstudentID, txtusername});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentProfileJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentProfileJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.Image","jpg","png");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);
        if (result==JFileChooser.APPROVE_OPTION){
            File selectedFile=file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            ImageIcon MyImage  =new ImageIcon(path);
            Image img = MyImage.getImage();
            Image newImg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
            image = new ImageIcon(newImg);
            lblImage.setIcon(image);
        }
        else if (result==JFileChooser.CANCEL_OPTION){
            System.out.println("No picture");
        }
    }//GEN-LAST:event_btnAddPhotoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGraduateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGraduateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name=txtsname.getText();
        String Gender=txtgender.getText();
        int age =Integer.parseInt(txtage.getText());
        String Email=txtEmail.getText();
        String region=txtregion.getText();
        String Language=txtlanguage.getText();
        LocalDate birthday= LocalDate.parse(txtbirthday.getText());
        int studentID=Integer.parseInt(txtstudentID.getText());
        String sUsername=txtusername.getText();
        double GPA=Double.parseDouble(txtGPA.getText());
        boolean isGraduate=Boolean.valueOf(txtGraduate.getText());

        student.setName(txtsname.getText());
        student.setGender(txtgender.getText());
        student.setAge(Integer.parseInt(txtage.getText()));
        student.setEmail(txtEmail.getText());
        student.setRegion(txtregion.getText());
        student.setLanguage(txtlanguage.getText());
        student.setBirthday(LocalDate.parse(txtbirthday.getText()));
        student.setStudentID(Integer.parseInt(txtstudentID.getText()));
        student.setsUsername(txtusername.getText());
        student.setGPA(Double.parseDouble(txtGPA.getText()));
        student.setIsGraduate(true);
        student.setImage((ImageIcon) lblImage.getIcon());

        JOptionPane.showMessageDialog(this, "Your personal information has been updated.");
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StudentProfileJPanel;
    private javax.swing.JButton btnAddPhoto;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAge1;
    private javax.swing.JLabel lblAge2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStuProfile;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblbirthday;
    private javax.swing.JLabel lblstudentID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGPA;
    private javax.swing.JTextField txtGraduate;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtbirthday;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtlanguage;
    private javax.swing.JTextField txtregion;
    private javax.swing.JTextField txtsname;
    private javax.swing.JTextField txtstudentID;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
