/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.awt.CardLayout;
import model.Admin;
import model.Student;
import model.Professor;
/**
 *
 * @author JANFAN
 */
public class StudentDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentDashboardJPanel
     */
    Student student;
    Admin admin;
    Professor professor;
    public StudentDashboardJPanel(Admin admin, Student student) {
        initComponents();
        this.admin=admin;
        this.student=student;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        workAreaPanel = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        btnShowCourse = new javax.swing.JButton();
        btnShowProfile = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        btnComment = new javax.swing.JButton();

        SplitPane.setBackground(new java.awt.Color(251, 238, 172));
        SplitPane.setDividerSize(20);

        workAreaPanel.setBackground(new java.awt.Color(251, 238, 172));

        javax.swing.GroupLayout workAreaPanelLayout = new javax.swing.GroupLayout(workAreaPanel);
        workAreaPanel.setLayout(workAreaPanelLayout);
        workAreaPanelLayout.setHorizontalGroup(
            workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        workAreaPanelLayout.setVerticalGroup(
            workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(workAreaPanel);

        controlPanel.setBackground(new java.awt.Color(251, 238, 172));

        btnShowCourse.setBackground(new java.awt.Color(117, 194, 246));
        btnShowCourse.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnShowCourse.setText("COURSE");
        btnShowCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCourseActionPerformed(evt);
            }
        });

        btnShowProfile.setBackground(new java.awt.Color(117, 194, 246));
        btnShowProfile.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnShowProfile.setText("PROFILE");
        btnShowProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowProfileActionPerformed(evt);
            }
        });

        btnSignOut.setBackground(new java.awt.Color(29, 93, 155));
        btnSignOut.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSignOut.setForeground(new java.awt.Color(255, 255, 255));
        btnSignOut.setText("SIGN OUT");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        btnComment.setBackground(new java.awt.Color(117, 194, 246));
        btnComment.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnComment.setText("Comment");
        btnComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnShowProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSignOut)
                            .addComponent(btnShowCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnComment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnShowCourse, btnShowProfile, btnSignOut});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnShowCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnShowProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnComment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        SplitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCourseActionPerformed
        // TODO add your handling code here:
        //CardLayout cardlayout=(CardLayout)this.getParent().getLayout();
        //cardlayout.show(this.getParent(),"studentDashboard");
        StudentCourseJPanel studentCourseJPanel=new StudentCourseJPanel(SplitPane,admin,student);
        SplitPane.setRightComponent(studentCourseJPanel);
    }//GEN-LAST:event_btnShowCourseActionPerformed

    private void btnShowProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowProfileActionPerformed
        // TODO add your handling code here:
        StudentProfileJPanel studentProfileJPanel=new StudentProfileJPanel(student);
        SplitPane.setRightComponent(studentProfileJPanel);
    }//GEN-LAST:event_btnShowProfileActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
        CardLayout cardlayout=(CardLayout)this.getParent().getLayout();
        cardlayout.show(this.getParent(),"studentSignIn");
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentActionPerformed
        // TODO add your handling code here:
        StudentCommentJPanel studentCommentJPanel=new StudentCommentJPanel(professor,admin);
        SplitPane.setRightComponent(studentCommentJPanel);
    }//GEN-LAST:event_btnCommentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnComment;
    private javax.swing.JButton btnShowCourse;
    private javax.swing.JButton btnShowProfile;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel workAreaPanel;
    // End of variables declaration//GEN-END:variables
}
